const FILTERS_DATA = {
    groups: {
        0: {
            id: 0, name: 'Custom', order: 99, filters: [],
        },
        1: {
            id: 1,
            name: 'Ad Blocking',
            order: 1,
            enabled: true,
            filters: [2, 11, 101, 204],
        },
        2: {
            id: 2,
            name: 'Privacy',
            order: 2,
            filters: [3, 118, 215, 225, 239],
            enabled: true,
        },
        3: {
            id: 3,
            name: 'Social Widgets',
            order: 3,
            filters: [4, 123],
            enabled: true,
        },
        4: {
            id: 4,
            name: 'Annoyances',
            order: 4,
            filters: [
                14, 122,
                201, 207,
                229, 241,
                209, 211,
            ],
            enabled: true,
        },
        5: {
            id: 5,
            name: 'Security',
            order: 5,
            filters: [208, 210, 242],
            enabled: true,
        },
        6: {
            id: 6,
            name: 'Other',
            order: 6,
            enabled: true,
            filters: [10, 12, 15, 5, 240],
        },
        7: {
            id: 7,
            name: 'Language-specific',
            order: 7,
            filters: [
                13, 16, 1, 6, 7, 8,
                9, 102, 103, 104, 105, 106,
                107, 108, 109, 110, 111, 112,
                113, 114, 115, 121, 202, 203,
                205, 206, 212, 213, 214, 216,
                217, 218, 219, 220, 221, 222,
                223, 224, 226, 227, 228, 230,
                231, 232, 233, 234, 235, 236,
                237, 238, 243, 244, 245, 246,
                247, 116, 117, 119, 120, 200,
                249,
            ],
            enabled: true,
        },
    },
    filters: {
        1: {
            id: 1,
            name: 'AdGuard Russian filter',
            description: 'Filter that enables ad blocking on websites in the Russian language.',
            homepage: 'https://kb.adguard.com/general/adguard-ad-filters#russian',
            version: '2.0.17.17',
            timeUpdated: 1561723341000,
            order: 1,
            languages: [
                'ru',
            ],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/1.txt',
            tags: [
                1,
                8,
                10,
                11,
            ],
            lastUpdateTime: 1562781732000,
            lastCheckTime: 1562783380232,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 7,
        },
        2: {
            id: 2,
            name: 'AdGuard Base filter',
            description: 'EasyList + AdGuard Base filter. This filter is necessary for quality ad blocking.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#english',
            version: '2.0.62.3',
            timeUpdated: 1561723358000,
            order: 1,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/2.txt',
            tags: [
                10,
                1,
                9,
                11,
            ],
            lastUpdateTime: 1562772646000,
            lastCheckTime: 1562775263141,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 1,
        },
        3: {
            id: 3,
            name: 'AdGuard Tracking Protection filter',
            description: 'The most comprehensive list of various online counters and web analytics tools. Use this filter, if you do not want your actions on the Internet to be tracked.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#spyware-filter',
            version: '2.0.7.80',
            timeUpdated: 1561723360000,
            order: 1,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/3.txt',
            tags: [
                2,
                10,
            ],
            lastUpdateTime: 1562873445000,
            lastCheckTime: 1562917845500,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 2,
        },
        4: {
            id: 4,
            name: 'AdGuard Social Media filter',
            description: 'Filter for social media widgets (\\"Like\\" buttons and such).',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#social-media-filter',
            version: '2.0.13.27',
            timeUpdated: 1561638650000,
            order: 1,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/4.txt',
            tags: [
                3,
                10,
            ],
            lastUpdateTime: 1562873449000,
            lastCheckTime: 1562917846098,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 3,
        },
        5: {
            id: 5,
            name: 'AdGuard Experimental filter',
            description: 'Filter designed to test certain hazardous filtering rules before they are added to the basic filters.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#experimental',
            version: '0.0.0.0',
            timeUpdated: 1552394422000,
            order: 4,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/5.txt',
            tags: [
                45,
            ],
            groupId: 6,
        },
        6: {
            id: 6,
            name: 'AdGuard German filter',
            description: 'EasyList Germany + AdGuard German filter. Filter list that specifically removes ads on websites in the German language.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#german',
            version: '0.0.0.0',
            timeUpdated: 1561591857000,
            order: 1,
            languages: [
                'de',
            ],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/6.txt',
            tags: [
                1,
                10,
                12,
                13,
            ],
            groupId: 7,
        },
        7: {
            id: 7,
            name: 'AdGuard Japanese filter',
            description: 'Filter that enables ad blocking on websites in the Japanese language.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#japanese-filter',
            version: '0.0.0.0',
            timeUpdated: 1561642286000,
            order: 1,
            languages: [
                'ja',
            ],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/7.txt',
            tags: [
                1,
                10,
                14,
            ],
            groupId: 7,
        },
        8: {
            id: 8,
            name: 'AdGuard Dutch filter',
            description: 'EasyList Dutch + AdGuard Dutch filter. Filter list that specifically removes ads on websites in the Dutch language.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#dutch-filter',
            version: '0.0.0.0',
            timeUpdated: 1560859397000,
            order: 1,
            languages: [
                'nl',
            ],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/8.txt',
            tags: [
                1,
                10,
                11,
                15,
                16,
            ],
            groupId: 7,
        },
        9: {
            id: 9,
            name: 'AdGuard Spanish/Portuguese filter',
            description: 'Filter list that specifically removes ads on websites in the Spanish and Portuguese languages.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#spanish-portuguese-filter',
            version: '0.0.0.0',
            timeUpdated: 1561559470000,
            order: 1,
            languages: [
                'es',
                'pt',
            ],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/9.txt',
            tags: [
                1,
                10,
                17,
                18,
            ],
            groupId: 7,
        },
        10: {
            id: 10,
            name: 'Filter unblocking search ads and self-promotion',
            description: 'Filter that unblocks searches (Duckduckgo, Google, Bing, Yahoo) and self-promo ads. Self-promotion definition: When an ad on a website is promoting this very website or other websites/social media/etc. closely related to it, such an ad is considered a self-promoting one.',
            homepage: 'https://kb.adguard.com/en/general/search-ads-and-self-promotion',
            version: '2.0.0.67',
            timeUpdated: 1560706208000,
            order: 1,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/10.txt',
            tags: [
                0,
            ],
            lastUpdateTime: 1562185806000,
            lastCheckTime: 1562775262392,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 6,
        },
        11: {
            id: 11,
            name: 'AdGuard Mobile Ads filter',
            description: 'Filter for all known mobile ad networks. Useful for mobile devices.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#mobile-ads-filter',
            version: '0.0.0.0',
            timeUpdated: 1561717810000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/11.txt',
            tags: [
                1,
                2,
                10,
                11,
                19,
            ],
            enabled: true,
            groupId: 1,
        },
        12: {
            id: 12,
            name: 'AdGuard Safari filter',
            description: 'Special filter for Safari 9+ on iOS and Mac OS. We need a separate filter for Safari browser because it does not fully support our rules syntax.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#safari-filter',
            version: '0.0.0.0',
            timeUpdated: 1561134612000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/12.txt',
            tags: [
                1,
                20,
                11,
                21,
                22,
                23,
                46,
            ],
            groupId: 6,
        },
        13: {
            id: 13,
            name: 'AdGuard Turkish filter',
            description: 'Filter list that specifically removes ads on websites in the Turkish language.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#turkish-filter',
            version: '0.0.0.0',
            timeUpdated: 1561494615000,
            order: 1,
            languages: [
                'tr',
            ],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/13.txt',
            tags: [
                1,
                10,
                11,
                24,
            ],
            groupId: 7,
        },
        14: {
            id: 14,
            name: 'AdGuard Annoyances filter',
            description: 'Blocks irritating elements on web pages including cookie notices, third-party widgets and in-page pop-ups.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#annoyances-filter',
            version: '2.0.23.79',
            timeUpdated: 1561723331000,
            order: 1,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/14.txt',
            tags: [
                5,
                10,
                11,
            ],
            lastUpdateTime: 1562884219000,
            lastCheckTime: 1562917846955,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 4,
        },
        15: {
            id: 15,
            name: 'AdGuard Simplified domain names filter',
            description: 'Filter composed from several other filters (AdGuard Base filter, Social Media filter, Tracking Protection filter, Mobile Ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#simplified-domain-names-filter',
            version: '0.0.0.0',
            timeUpdated: 1561656620000,
            order: 3,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/15.txt',
            tags: [
                45,
                1,
                2,
                9,
                11,
                25,
                26,
                13,
                58,
                59,
                60,
                61,
            ],
            groupId: 6,
        },
        16: {
            id: 16,
            name: 'AdGuard French filter',
            description: 'Liste FR + AdGuard French filter. Filter list that specifically removes ads on websites in the French language.',
            homepage: 'https://kb.adguard.com/en/general/adguard-ad-filters#french-filter',
            version: '0.0.0.0',
            timeUpdated: 1561588223000,
            order: 1,
            languages: [
                'fr',
            ],
            expires: 172800,
            subscriptionUrl: 'https://filters.adtidy.org/extension/chromium/filters/16.txt',
            tags: [
                1,
                10,
                11,
                27,
                28,
            ],
            groupId: 7,
        },
        101: {
            id: 101,
            name: 'EasyList',
            description: 'EasyList is the primary subscription that removes adverts from web pages in English language.',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723217000,
            order: 3,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist.to/easylist/easylist.txt',
            tags: [
                1,
            ],
            enabled: true,
            groupId: 1,
        },
        102: {
            id: 102,
            name: 'ABPindo',
            description: 'Bahasa Indonesia supplement for EasyList.',
            homepage: 'http://abpindo.blogspot.com/',
            version: '0.0.0.0',
            timeUpdated: 1561453219000,
            order: 2,
            languages: [
                'id',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt',
            tags: [
                1,
                9,
                10,
                29,
            ],
            groupId: 7,
        },
        103: {
            id: 103,
            name: 'Bulgarian list',
            description: 'български supplement for EasyList.',
            homepage: 'http://stanev.org/abp/',
            version: '0.0.0.0',
            timeUpdated: 1552921217000,
            order: 2,
            languages: [
                'bg',
            ],
            expires: 172800,
            subscriptionUrl: 'http://stanev.org/abp/adblock_bg.txt',
            tags: [
                1,
                9,
                10,
                30,
            ],
            groupId: 7,
        },
        104: {
            id: 104,
            name: 'EasyList China',
            description: '中文 supplement for EasyList',
            homepage: 'http://abpchina.org/forum/',
            version: '0.0.0.0',
            timeUpdated: 1561723221000,
            order: 2,
            languages: [
                'zh',
            ],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/easylistchina.txt',
            tags: [
                1,
                9,
                10,
                31,
            ],
            groupId: 7,
        },
        105: {
            id: 105,
            name: 'EasyList Czech and Slovak',
            description: 'čeština, slovenčina supplement for EasyList',
            homepage: 'https://github.com/tomasko126/easylistczechandslovak',
            version: '0.0.0.0',
            timeUpdated: 1561658424000,
            order: 2,
            languages: [
                'cs',
                'sk',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt',
            tags: [
                1,
                9,
                10,
                32,
                33,
            ],
            groupId: 7,
        },
        106: {
            id: 106,
            name: 'EasyList Dutch',
            description: 'Nederlands supplement for EasyList',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723222000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/easylistdutch.txt',
            tags: [
                1,
                9,
                15,
            ],
            groupId: 7,
        },
        107: {
            id: 107,
            name: 'EasyList Germany',
            description: 'Deutsch supplement for EasyList',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561485634000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist.to/easylistgermany/easylistgermany.txt',
            tags: [
                1,
                9,
                12,
            ],
            groupId: 7,
        },
        108: {
            id: 108,
            name: 'EasyList Hebrew',
            description: 'Supplement for EasyList. Language: עברית',
            homepage: 'https://github.com/easylist/EasyListHebrew',
            version: '0.0.0.0',
            timeUpdated: 1561658427000,
            order: 2,
            languages: [
                'he',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt',
            tags: [
                1,
                9,
                10,
                34,
            ],
            groupId: 7,
        },
        109: {
            id: 109,
            name: 'EasyList Italy',
            description: 'italiano supplement for EasyList',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723225000,
            order: 2,
            languages: [
                'it',
            ],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/easylistitaly.txt',
            tags: [
                1,
                9,
                10,
                35,
            ],
            groupId: 7,
        },
        110: {
            id: 110,
            name: 'EasyList Lithuania',
            description: 'lietuvių kalba supplement for EasyList',
            homepage: 'http://margevicius.lt/',
            version: '0.0.0.0',
            timeUpdated: 1551258023000,
            order: 2,
            languages: [
                'lt',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt',
            tags: [
                1,
                9,
                10,
                37,
            ],
            groupId: 7,
        },
        111: {
            id: 111,
            name: 'Latvian List',
            description: 'latviešu valoda supplement for EasyList',
            homepage: 'https://notabug.org/latvian-list/adblock-latvian',
            version: '0.0.0.0',
            timeUpdated: 1551776434000,
            order: 2,
            languages: [
                'lv',
            ],
            expires: 172800,
            subscriptionUrl: 'https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt',
            tags: [
                1,
                9,
                10,
                36,
            ],
            groupId: 7,
        },
        112: {
            id: 112,
            name: 'Liste AR',
            description: 'Supplement for EasyList. Language: العربية',
            homepage: 'https://code.google.com/p/liste-ar-adblock/',
            version: '0.0.0.0',
            timeUpdated: 1561723233000,
            order: 2,
            languages: [
                'ar',
            ],
            expires: 172800,
            subscriptionUrl: 'https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt',
            tags: [
                1,
                9,
                10,
                38,
            ],
            groupId: 7,
        },
        113: {
            id: 113,
            name: 'Liste FR',
            description: 'français supplement for EasyList',
            homepage: 'http://adblock-listefr.com/',
            version: '0.0.0.0',
            timeUpdated: 1561723235000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/liste_fr.txt',
            tags: [
                1,
                9,
                27,
            ],
            groupId: 7,
        },
        114: {
            id: 114,
            name: 'ROList',
            description: 'românesc supplement for EasyList',
            homepage: 'http://www.zoso.ro/rolist',
            version: '0.0.0.0',
            timeUpdated: 1559757629000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://www.zoso.ro/pages/rolist.txt',
            tags: [
                1,
                9,
                39,
            ],
            groupId: 7,
        },
        115: {
            id: 115,
            name: 'RU AdList',
            description: 'Дополнительная подписка к EasyList для русскоязычных сайтов',
            homepage: 'https://forums.lanik.us/viewforum.php?f=102',
            version: '0.0.0.0',
            timeUpdated: 1561723245000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt',
            tags: [
                1,
                8,
                9,
            ],
            groupId: 7,
        },
        116: {
            id: 116,
            name: '(Obsolete) Wiltteri',
            description: 'Finnish supplement list for EasyList',
            homepage: 'https://github.com/wiltteri/',
            version: '0.0.0.0',
            timeUpdated: 1512386377000,
            order: 100,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt',
            tags: [
                1,
                9,
                40,
                46,
            ],
            groupId: 7,
        },
        117: {
            id: 117,
            name: 'Polskie Filtry Wewnętrzne',
            description: 'Polskie Filtry Wewnętrzne',
            homepage: 'https://github.com/KonoromiHimaries/PolishSubFilters',
            version: '0.0.0.0',
            timeUpdated: 1561572042000,
            order: 100,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/KonoromiHimaries/PolishSubFilters/master/internal-filters/wewnetrzne.txt',
            tags: [
                5,
                9,
                41,
            ],
            groupId: 7,
        },
        118: {
            id: 118,
            name: 'EasyPrivacy',
            description: 'Privacy protection supplement for EasyList.',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723247000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist.to/easylist/easyprivacy.txt',
            tags: [
                2,
            ],
            groupId: 2,
        },
        119: {
            id: 119,
            name: 'Icelandic ABP List',
            description: 'íslenska supplement for EasyList',
            homepage: 'http://adblock.gardar.net/',
            version: '0.0.0.0',
            timeUpdated: 1512386377000,
            order: 100,
            languages: [
                'is',
            ],
            expires: 172800,
            subscriptionUrl: 'https://adblock.gardar.net/is.abp.txt',
            tags: [
                1,
                9,
                10,
                42,
            ],
            groupId: 7,
        },
        120: {
            id: 120,
            name: '(Obsolete) Norsk adblockliste',
            description: 'norsk supplement for EasyList',
            homepage: 'http://home.fredfiber.no/langsholt/',
            version: '0.0.0.0',
            timeUpdated: 1512386377000,
            order: 100,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://home.fredfiber.no/langsholt/adblock.txt',
            tags: [
                1,
                9,
                43,
                46,
            ],
            groupId: 7,
        },
        121: {
            id: 121,
            name: 'Greek AdBlock Filter',
            description: 'ελληνικά supplement for EasyList',
            homepage: 'https://github.com/kargig/greek-adblockplus-filter',
            version: '0.0.0.0',
            timeUpdated: 1555178440000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://www.void.gr/kargig/void-gr-filters.txt',
            tags: [
                1,
                9,
                44,
            ],
            groupId: 7,
        },
        122: {
            id: 122,
            name: "Fanboy's Annoyances",
            description: "removes online annoyances (includes Fanboy's Social Blocking List) — supplement for EasyList",
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723254000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt',
            tags: [
                5,
                9,
            ],
            groupId: 4,
        },
        123: {
            id: 123,
            name: "Fanboy's Social Blocking List",
            description: 'removes social media integration — supplement for EasyList',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723256000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/fanboy-social.txt',
            tags: [
                3,
                9,
            ],
            groupId: 3,
        },
        200: {
            id: 200,
            name: 'ABP Japanese Filters',
            description: '日本語',
            homepage: 'https://code.google.com/p/adblock-plus-japanese-filter/',
            version: '0.0.0.0',
            timeUpdated: 1561550479000,
            order: 100,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt',
            tags: [
                1,
                2,
                14,
                45,
            ],
            groupId: 7,
        },
        201: {
            id: 201,
            name: 'Web Annoyances Ultralist',
            description: 'Block annoying web elements and reclaim lost screen real estate.',
            homepage: 'https://github.com/yourduskquibbles/webannoyances/',
            version: '0.0.0.0',
            timeUpdated: 1561701649000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt',
            tags: [
                5,
            ],
            groupId: 4,
        },
        202: {
            id: 202,
            name: 'Filtros Nauscopicos',
            description: 'español',
            homepage: 'http://nauscopio.nireblog.com/cat/filtrado',
            version: '0.0.0.0',
            timeUpdated: 1551378034000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://abp.mozilla-hispano.org/nauscopio/filtros.txt',
            tags: [
                1,
                17,
            ],
            groupId: 7,
        },
        203: {
            id: 203,
            name: 'hufilter',
            description: 'magyar',
            homepage: 'https://github.com/hufilter/hufilter/wiki',
            version: '0.0.0.0',
            timeUpdated: 1561280457000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter.txt',
            tags: [
                1,
                48,
            ],
            groupId: 7,
        },
        204: {
            id: 204,
            name: "Peter Lowe's list",
            description: 'English',
            homepage: 'http://pgl.yoyo.org/adservers/',
            version: '0.0.0.0',
            timeUpdated: 1561723265000,
            order: 4,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext',
            tags: [
                1,
                7,
            ],
            enabled: true,
            groupId: 1,
        },
        205: {
            id: 205,
            name: '(Obsolete) Schacks Adblock Plus liste',
            description: 'dansk',
            homepage: 'http://henrik.schack.dk/adblock/',
            version: '0.0.0.0',
            timeUpdated: 1551378036000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://adblock.schack.dk/block.txt',
            tags: [
                1,
                49,
                46,
            ],
            groupId: 7,
        },
        206: {
            id: 206,
            name: 'Xfiles',
            description: 'italiano',
            homepage: 'http://noads.it/',
            version: '0.0.0.0',
            timeUpdated: 1561464067000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://dl.dropboxusercontent.com/u/1289327/abpxfiles/filtri.txt',
            tags: [
                1,
                35,
            ],
            groupId: 7,
        },
        207: {
            id: 207,
            name: 'Adblock Warning Removal List',
            description: 'removes anti-adblock warnings and other obtrusive messages',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723268000,
            order: 3,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt',
            tags: [
                50,
            ],
            groupId: 4,
        },
        208: {
            id: 208,
            name: 'Malware Domains',
            description: 'malware protection',
            homepage: 'http://malwaredomains.com/',
            version: '2.0.43.81',
            timeUpdated: 1561723270000,
            order: 1,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/malwaredomains_full.txt',
            tags: [
                4,
            ],
            lastUpdateTime: 1562911257000,
            lastCheckTime: 1562917851755,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 5,
        },
        209: {
            id: 209,
            name: '(Obsolete) Prebake',
            description: 'Filters obtrusive EU cookie law notices',
            homepage: 'http://liamja.co.uk/Prebake/',
            version: '0.0.0.0',
            timeUpdated: 1528551692000,
            order: 100,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt',
            tags: [
                46,
                5,
            ],
            groupId: 4,
        },
        210: {
            id: 210,
            name: 'Spam404',
            description: 'This filter protects you from online scams',
            homepage: 'http://www.spam404.com/',
            version: '2.0.1.33',
            timeUpdated: 1561129263000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt',
            tags: [
                4,
            ],
            lastUpdateTime: 1562101259000,
            lastCheckTime: 1562917852321,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 5,
        },
        211: {
            id: 211,
            name: '(Obsolete) Anti-Adblock Killer | Reek',
            description: 'Anti-Adblock Killer | Filters for Adblockers',
            homepage: 'https://github.com/reek/anti-adblock-killer',
            version: '0.0.0.0',
            timeUpdated: 1512386377000,
            order: 100,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt',
            tags: [
                46,
                50,
            ],
            groupId: 4,
        },
        212: {
            id: 212,
            name: 'RU AdList: Counters',
            description: 'Дополнение для блокировки счетчиков',
            homepage: 'https://forums.lanik.us/viewforum.php?f=102',
            version: '0.0.0.0',
            timeUpdated: 1561723275000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/cntblock.txt',
            tags: [
                2,
                8,
            ],
            groupId: 7,
        },
        213: {
            id: 213,
            name: 'RU AdList: BitBlock',
            description: 'Дополнение для блокировки элементов сайтов, которые не относятся к основному содержимому сайта',
            homepage: 'https://forums.lanik.us/viewforum.php?f=102',
            version: '0.0.0.0',
            timeUpdated: 1561723279000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/bitblock.txt',
            tags: [
                5,
                8,
                3,
            ],
            groupId: 7,
        },
        214: {
            id: 214,
            name: 'ABPVN List',
            description: 'vietnamese',
            homepage: 'http://abpvn.com/',
            version: '0.0.0.0',
            timeUpdated: 1561636862000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn.txt',
            tags: [
                1,
                52,
            ],
            groupId: 7,
        },
        215: {
            id: 215,
            name: "Fanboy's Enhanced Tracking List",
            description: 'filters',
            homepage: 'https://secure.fanboy.co.nz/',
            version: '0.0.0.0',
            timeUpdated: 1561258863000,
            order: 3,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://secure.fanboy.co.nz/enhancedstats.txt',
            tags: [
                2,
            ],
            groupId: 2,
        },
        216: {
            id: 216,
            name: 'Official Polish filters for AdBlock, uBlock Origin & AdGuard',
            description: 'Oficjalne polskie filtry do AdBlocka, uBlocka Origin i AdGuarda',
            homepage: 'https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard',
            version: '0.0.0.0',
            timeUpdated: 1561712468000,
            order: 2,
            languages: [
                'pl',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt',
            tags: [
                1,
                10,
                41,
            ],
            groupId: 7,
        },
        217: {
            id: 217,
            name: 'Polskie Filtry Ciasteczkowe',
            description: 'polski filtr cookies',
            homepage: 'https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard',
            version: '0.0.0.0',
            timeUpdated: 1561572080000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt',
            tags: [
                6,
                41,
            ],
            groupId: 7,
        },
        218: {
            id: 218,
            name: 'Estonian List',
            description: 'Estonian filtr',
            homepage: 'http://adblock.ee/',
            version: '0.0.0.0',
            timeUpdated: 1556326066000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://adblock.ee/list.php',
            tags: [
                1,
                53,
            ],
            groupId: 7,
        },
        219: {
            id: 219,
            name: 'ChinaList+EasyList',
            description: 'China List and Easy List',
            homepage: 'http://www.adtchrome.com/extension/adt-chinalist-easylist.html',
            version: '0.0.0.0',
            timeUpdated: 1561280477000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://sub.adtchrome.com/adt-chinalist-easylist.txt',
            tags: [
                1,
                9,
                31,
            ],
            groupId: 7,
        },
        220: {
            id: 220,
            name: "CJX's Annoyance List",
            description: "CJX's Annoyance List",
            homepage: 'http://abpchina.org/forum/forum.php?mod=viewthread&tid=29667',
            version: '0.0.0.0',
            timeUpdated: 1561183279000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt',
            tags: [
                5,
                31,
            ],
            groupId: 7,
        },
        221: {
            id: 221,
            name: 'Polskie Filtry Społecznościowe',
            description: 'Polski social filtr',
            homepage: 'https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard',
            version: '0.0.0.0',
            timeUpdated: 1561572093000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt',
            tags: [
                3,
                41,
            ],
            groupId: 7,
        },
        222: {
            id: 222,
            name: 'Adblock-Persian list',
            description: 'Adblock-Persian list',
            homepage: 'http://ideone.com/K452p',
            version: '0.0.0.0',
            timeUpdated: 1535558408000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://ideone.com/plain/K452p',
            tags: [
                1,
                54,
            ],
            groupId: 7,
        },
        223: {
            id: 223,
            name: "Fanboy's Swedish",
            description: "Fanboy's Swedish",
            homepage: 'http://www.fanboy.co.nz/',
            version: '0.0.0.0',
            timeUpdated: 1560297721000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://www.fanboy.co.nz/fanboy-swedish.txt',
            tags: [
                1,
                55,
            ],
            groupId: 7,
        },
        224: {
            id: 224,
            name: 'Korean Adblock List',
            description: 'Korean Adblock List',
            homepage: 'https://github.com/gfmaster/adblock-korea-contrib',
            version: '0.0.0.0',
            timeUpdated: 1551378064000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/gfmaster/adblock-korea-contrib/master/filter.txt',
            tags: [
                1,
                56,
            ],
            groupId: 7,
        },
        225: {
            id: 225,
            name: 'Fanboy Anti-Facebook List',
            description: 'Warning, will break on facebook-based comment sites and may also break on some facebook apps or games.',
            homepage: 'http://www.fanboy.co.nz',
            version: '0.0.0.0',
            timeUpdated: 1560297721000,
            order: 4,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://www.fanboy.co.nz/fanboy-antifacebook.txt',
            tags: [
                2,
                45,
            ],
            groupId: 2,
        },
        226: {
            id: 226,
            name: "Fanboy's Vietnamese",
            description: "Fanboy's Vietnamese",
            homepage: 'http://www.fanboy.co.nz/',
            version: '0.0.0.0',
            timeUpdated: 1560297722000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://www.fanboy.co.nz/fanboy-vietnam.txt',
            tags: [
                1,
                52,
            ],
            groupId: 7,
        },
        227: {
            id: 227,
            name: 'List-KR',
            description: 'Filter that enables removing of ads, trackers, and various scripts from websites with Korean content. Based on Corset, Korean Adblock filter, Youslist. Combined and augmented with AdGuard-specific rules for enhanced filtering This filter is expected to be used alongside with English filter.',
            homepage: 'https://list-kr.github.io/',
            version: '0.0.0.0',
            timeUpdated: 1561723298000,
            order: 2,
            languages: [
                'ko',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/List-KR/List-KR/master/filter.txt',
            tags: [
                1,
                2,
                11,
                56,
                10,
            ],
            groupId: 7,
        },
        228: {
            id: 228,
            name: 'xinggsf',
            description: 'One more China filter by',
            homepage: 'https://github.com/xinggsf/Adblock-Plus-Rule',
            version: '0.0.0.0',
            timeUpdated: 1560265302000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt',
            tags: [
                1,
                31,
            ],
            groupId: 7,
        },
        229: {
            id: 229,
            name: "I don't care about cookies",
            description: "I don't care about cookies",
            homepage: 'https://www.i-dont-care-about-cookies.eu/',
            version: '0.0.0.0',
            timeUpdated: 1558083684000,
            order: 4,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://www.i-dont-care-about-cookies.eu/abp/',
            tags: [
                6,
            ],
            groupId: 4,
        },
        230: {
            id: 230,
            name: 'FanboyEspanol',
            description: 'Fanboys Spanish/Portuguese',
            homepage: 'https://adblockplus.org/subscriptions',
            version: '0.0.0.0',
            timeUpdated: 1560297727000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'http://fanboy.co.nz/fanboy-espanol.txt',
            tags: [
                1,
                17,
            ],
            groupId: 7,
        },
        231: {
            id: 231,
            name: 'Easylist Spanish',
            description: 'EasyList Spanish filter subscription',
            homepage: 'https://hg.adblockplus.org/easylistspanish',
            version: '0.0.0.0',
            timeUpdated: 1561723303000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/easylistspanish.txt',
            tags: [
                1,
                9,
                17,
            ],
            groupId: 7,
        },
        232: {
            id: 232,
            name: 'KAD - Przekręty',
            description: 'Filtr chroniący przed przekrętami takimi jak subskrypcje SMS',
            homepage: 'https://kadantiscam.netlify.com/',
            version: '0.0.0.0',
            timeUpdated: 1561669291000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/PolishFiltersTeam/KAD/master/KAD.txt',
            tags: [
                4,
                41,
            ],
            groupId: 7,
        },
        233: {
            id: 233,
            name: 'Adblock List for Finland',
            description: 'Finnish adblock list',
            homepage: 'https://github.com/theel0ja/finnish-easylist-addition',
            version: '0.0.0.0',
            timeUpdated: 1560988905000,
            order: 2,
            languages: [
                'fi',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/theel0ja/finnish-easylist-addition/master/Finland_adb.txt',
            tags: [
                1,
                10,
                40,
            ],
            groupId: 7,
        },
        234: {
            id: 234,
            name: 'ROLIST2',
            description: 'This is a complementary list for RoList with annoyances that are not necessarily banners',
            homepage: 'https://zoso.ro/rolist/',
            version: '0.0.0.0',
            timeUpdated: 1557295313000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://www.zoso.ro/pages/rolist2.txt',
            tags: [
                5,
                39,
                57,
            ],
            groupId: 7,
        },
        235: {
            id: 235,
            name: 'Iranian filter',
            description: 'Adblock Iran filter',
            homepage: 'https://github.com/farrokhi/adblock-iran',
            version: '0.0.0.0',
            timeUpdated: 1558515688000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://gitcdn.xyz/repo/farrokhi/adblock-iran/master/filter.txt',
            tags: [
                1,
                54,
            ],
            groupId: 7,
        },
        236: {
            id: 236,
            name: 'road-block',
            description: 'Romanian Ad (ROad) filter subscription',
            homepage: 'https://github.com/tcptomato/ROad-Block',
            version: '0.0.0.0',
            timeUpdated: 1560870106000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/tcptomato/ROad-Block/master/road-block-filters.txt',
            tags: [
                1,
                39,
            ],
            groupId: 7,
        },
        237: {
            id: 237,
            name: 'Polskie Filtry Elementów Irytujących',
            description: 'Filters that hide and block pop-ups, widgets, newsletters, push notifications, arrows and other irritating elements (include Polish Cookies Filters)',
            homepage: 'https://polishannoyancefilters.netlify.com',
            version: '0.0.0.0',
            timeUpdated: 1561723308000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt',
            tags: [
                41,
                5,
            ],
            groupId: 7,
        },
        238: {
            id: 238,
            name: 'Polish Anti Adblock Filters',
            description: 'Oficjalne polskie filtry przeciwko alertom o Adblocku',
            homepage: 'https://github.com/olegwukr/polish-privacy-filters',
            version: '0.0.0.0',
            timeUpdated: 1561669296000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/anti-adblock.txt',
            tags: [
                50,
                41,
            ],
            groupId: 7,
        },
        239: {
            id: 239,
            name: "Fanboy's Anti-thirdparty Fonts",
            description: 'A filter to block third-party fonts. (May break the look and design of some websites)',
            homepage: 'http://www.fanboy.co.nz/',
            version: '0.0.0.0',
            timeUpdated: 1560297733000,
            order: 5,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://fanboy.co.nz/fanboy-antifonts.txt',
            tags: [
                2,
                45,
            ],
            groupId: 2,
        },
        240: {
            id: 240,
            name: 'BarbBlock',
            description: 'BarbBlock is a content blocking list with standalone browser extensions for Chrome and Firefox. It blacklists sites which have used DMCA takedowns to force removal from other content blocking lists. Such takedowns are categorically invalid, but they can be effective at intimidating small open-source projects into compliance.',
            homepage: 'https://ssl.bblck.me/',
            version: '0.0.0.0',
            timeUpdated: 1559563320000,
            order: 5,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://ssl.bblck.me/blacklists/adblock-plus.txt',
            tags: [
                0,
            ],
            groupId: 6,
        },
        241: {
            id: 241,
            name: "Fanboy's Cookiemonster List",
            description: "This will remove cookie and privacy warnings (List already included in Annoyances List, don't add list if you're using the Annoyances List)",
            homepage: 'http://www.fanboy.co.nz/',
            version: '0.0.0.0',
            timeUpdated: 1561723315000,
            order: 5,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://www.fanboy.co.nz/fanboy-cookiemonster.txt',
            tags: [
                6,
            ],
            groupId: 4,
        },
        242: {
            id: 242,
            name: 'NoCoin Filter List',
            description: 'This filter disables browser based miners such as coin-hive.',
            homepage: 'https://github.com/hoshsadiq/adblock-nocoin-list/',
            version: '1.0.1.82',
            timeUpdated: 1561334503000,
            order: 3,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt',
            tags: [
                4,
            ],
            lastUpdateTime: 1562868104000,
            lastCheckTime: 1562917853044,
            loaded: true,
            installed: true,
            enabled: true,
            groupId: 5,
        },
        243: {
            id: 243,
            name: "Frellwit's Swedish Filter",
            description: 'A filter for uBlock Origin that aims to remove regional Swedish ads, tracking, social media, annoyances, sponsored articles etc.',
            homepage: 'https://github.com/lassekongo83/Frellwit-s-filter-lists',
            version: '0.0.0.0',
            timeUpdated: 1561615294000,
            order: 2,
            languages: [
                'sv',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Filter.txt',
            tags: [
                10,
                1,
                5,
                2,
                3,
                55,
            ],
            groupId: 7,
        },
        244: {
            id: 244,
            name: 'YousList',
            description: 'Filter that blocks ads on Korean sites.',
            homepage: 'https://github.com/yous/YousList/',
            version: '0.0.0.0',
            timeUpdated: 1561604501000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/yous/YousList/master/youslist.txt',
            tags: [
                1,
                56,
            ],
            groupId: 7,
        },
        245: {
            id: 245,
            name: 'AlleBlock',
            description: 'Filters that removes annoying elements from Polish e-commerce sites',
            homepage: 'https://github.com/maciejtarmas/AlleBlock',
            version: '0.0.0.0',
            timeUpdated: 1561582902000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://alleblock.pl/alleblock/alleblock.txt',
            tags: [
                41,
                5,
            ],
            groupId: 7,
        },
        246: {
            id: 246,
            name: 'EasyList Polish',
            description: 'Polish supplement for EasyList',
            homepage: 'https://easylist.to/',
            version: '0.0.0.0',
            timeUpdated: 1561723318000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://easylist-downloads.adblockplus.org/easylistpolish.txt',
            tags: [
                1,
                9,
                41,
            ],
            groupId: 7,
        },
        247: {
            id: 247,
            name: 'Polskie Filtry RSS',
            description: 'The list is a supplement to Polish social filters for blocking RSS elements.',
            homepage: 'https://github.com/PolishFiltersTeam/PolishRSSFilters',
            version: '0.0.0.0',
            timeUpdated: 1561334506000,
            order: 2,
            languages: [],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/PolishFiltersTeam/PolishRSSFilters/master/polish_rss_filters.txt',
            tags: [
                41,
                5,
                62,
            ],
            groupId: 7,
        },
        249: {
            id: 249,
            name: "Dandelion Sprout's Nordic Filters",
            description: "This list covers websites for Norway, Denmark, Iceland, Danish territories, and the Sami indigenous population. For more information, details, helpful tools, and other lists that I've made, visit https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#english.",
            homepage: 'https://github.com/DandelionSprout/adfilt',
            version: '0.0.0.0',
            timeUpdated: 1560988920000,
            order: 249,
            languages: [
                'no',
                'da',
                'is',
                'fo',
            ],
            expires: 172800,
            subscriptionUrl: 'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt',
            tags: [
                10,
                1,
                4,
                43,
                49,
                42,
                63,
            ],
            groupId: 7,
        },
    },
    tags: {
        1: {
            keyword: 'ads',
            name: 'Ad Blocking',
            description: 'Designed to block ads online',
            id: 1,
        },
        2: {
            keyword: 'privacy',
            name: 'Privacy protection',
            description: 'Designed to protect your privacy online by blocking trackers and analytics',
            id: 2,
        },
        3: {
            keyword: 'social',
            name: 'Social widgets blocking',
            description: 'Designed to block social media elements (widgets, \\"Like\\" buttons etc.)',
            id: 3,
        },
        4: {
            keyword: 'security',
            name: 'Protection against malware and fraud',
            description: 'Designed to protect you from malicious and dangerous websites',
            id: 4,
        },
        5: {
            keyword: 'annoyances',
            name: 'Anti-annoyances protection',
            description: 'Designed to block non-ads elements that distract you from the content (subscription offers, promotion notices etc.).',
            id: 5,
        },
        6: {
            keyword: 'cookies',
            name: 'Cookie notices blocking',
            description: 'Designed to block cookie notices on websites',
            id: 6,
        },
        7: {
            keyword: 'lang:en',
            name: 'English language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the English language',
            id: 7,
        },
        8: {
            keyword: 'lang:ru',
            name: 'Russian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Russian language',
            id: 8,
        },
        10: {
            keyword: 'recommended',
            name: 'AdGuard recommendation',
            description: 'Recommended to use with AdGuard ad blocker',
            id: 10,
        },
        12: {
            keyword: 'lang:de',
            name: 'German language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the German language',
            id: 12,
        },
        14: {
            keyword: 'lang:ja',
            name: 'Japanese language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Japanese language',
            id: 14,
        },
        15: {
            keyword: 'lang:nl',
            name: 'Dutch language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Dutch language',
            id: 15,
        },
        17: {
            keyword: 'lang:es',
            name: 'Spanish language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Spanish language',
            id: 17,
        },
        18: {
            keyword: 'lang:pt',
            name: 'Portuguese language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Portuguese language',
            id: 18,
        },
        19: {
            keyword: 'mobile',
            name: 'For mobile devices',
            description: 'Designed specifically to block ads and trackers on mobile devices',
            id: 19,
        },
        20: {
            keyword: 'unbreak',
            name: 'Compatibility',
            description: 'Contains set of rules to fix compatibility issues',
            id: 20,
        },
        21: {
            keyword: 'ios',
            name: 'iOS-specific',
            description: 'Designed specifically to work on iOS-based devices',
            id: 21,
        },
        22: {
            keyword: 'ext_safari',
            name: 'Safari-specific',
            description: 'Designed specifically to work with Safari browser content blockers',
            id: 22,
        },
        23: {
            keyword: 'ext_android_cb',
            name: 'Compatibility',
            description: 'Contains set of rules to fix compatibility issues',
            id: 23,
        },
        24: {
            keyword: 'lang:tr',
            name: 'Turkish language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Turkish language',
            id: 24,
        },
        27: {
            keyword: 'lang:fr',
            name: 'French language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the French language',
            id: 27,
        },
        29: {
            keyword: 'lang:id',
            name: 'Indonesian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Indonesian language',
            id: 29,
        },
        30: {
            keyword: 'lang:bg',
            name: 'Bulgarian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Bulgarian language',
            id: 30,
        },
        31: {
            keyword: 'lang:zh',
            name: 'Chinese language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Chinese language',
            id: 31,
        },
        32: {
            keyword: 'lang:cs',
            name: 'Czech language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Czech language',
            id: 32,
        },
        33: {
            keyword: 'lang:sk',
            name: 'Slovak language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Slovak language',
            id: 33,
        },
        34: {
            keyword: 'lang:he',
            name: 'Hebrew language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the  Hebrew language',
            id: 34,
        },
        35: {
            keyword: 'lang:it',
            name: 'Italian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Italian language',
            id: 35,
        },
        36: {
            keyword: 'lang:lv',
            name: 'Latvian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Latvian language',
            id: 36,
        },
        37: {
            keyword: 'lang:lt',
            name: 'Lithuanian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Lithuanian language',
            id: 37,
        },
        38: {
            keyword: 'lang:ar',
            name: 'Arabic language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the  Arabic language',
            id: 38,
        },
        39: {
            keyword: 'lang:ro',
            name: 'Romanian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Romanian language',
            id: 39,
        },
        40: {
            keyword: 'lang:fi',
            name: 'Finnish language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Finnish language',
            id: 40,
        },
        41: {
            keyword: 'lang:pl',
            name: 'Polish language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Polish language',
            id: 41,
        },
        42: {
            keyword: 'lang:is',
            name: 'Icelandic language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Icelandic language',
            id: 42,
        },
        43: {
            keyword: 'lang:no',
            name: 'Norwegian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Norwegian language',
            id: 43,
        },
        44: {
            keyword: 'lang:el',
            name: 'Greek language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Greek language',
            id: 44,
        },
        45: {
            keyword: 'problematic',
            name: 'Potentially problematic',
            description: 'Can cause issues depending on your ad blocker and the specific website',
            id: 45,
        },
        46: {
            keyword: 'obsolete',
            name: 'Obsolete',
            description: 'Outdated or not supported anymore',
            id: 46,
        },
        48: {
            keyword: 'lang:hu',
            name: 'Hungarian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in  the Hungarian language',
            id: 48,
        },
        49: {
            keyword: 'lang:da',
            name: 'Danish language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Danish language',
            id: 49,
        },
        50: {
            keyword: 'antiadblock',
            name: 'Protection from adblock circumvention scripts',
            description: 'Designed to resist adblock circumvention scripts on websites',
            id: 50,
        },
        52: {
            keyword: 'lang:vi',
            name: 'Vietnamese language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Vietnamese language',
            id: 52,
        },
        53: {
            keyword: 'lang:et',
            name: 'Estonian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Estonian language',
            id: 53,
        },
        54: {
            keyword: 'lang:fa',
            name: 'Persian language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Persian language',
            id: 54,
        },
        55: {
            keyword: 'lang:sv',
            name: 'Swedish language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Swedish language',
            id: 55,
        },
        56: {
            keyword: 'lang:ko',
            name: 'Korean language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Korean language',
            id: 56,
        },
        63: {
            keyword: 'lang:fo',
            name: 'Faroese language-specific ad blocking',
            description: 'Designed specifically to block ads on web pages in the Faroese language',
            id: 63,
        },
    },
};

// eslint-disable-next-line import/prefer-default-export
export { FILTERS_DATA };
